### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by amanuelemma** [WhiteboardLiveCoding/ImageSegmentation#4]
anyone can help me to use this ? needs some simplicity and use direction !
Thank you!

**Comment by mishrabhinav** [comment]
Hi @amanuelemma. Sorry about the lack of documentation. The library in its current form is useful only for handwritten text. You can take a look at [these](https://github.com/WhiteboardLiveCoding/WhiteboardLiveCoding/blob/master/WLC/web_endpoint.py#L38-L46) lines to see how we have used this library in other places. Please let me know if you need help with anything else.

**Comment by amanuelemma** [comment]
Thank You Dear!
